### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by AJNDL** [nacgarg/frc-scouting#1]
![bug](https://cloud.githubusercontent.com/assets/4275909/6519064/d778e1a2-c363-11e4-818a-0ae5f70904a7.png)

**Comment by vanessachen** [comment]
Hey Nachi/AJ,
What exactly is this error?
-Vanessa

**Comment by AJNDL** [comment]
@vanessachen it means that on line 16, at the 49th character (including spaces), the code tried to find the property `name` of an object that was undefined. This could mean it tried to run `var foo = bar.name` and bar was undefined, or `var foo = bar['name']` as well.

**Comment by AJNDL** [comment]
@vanessachen @nacgarg but here it means that in the line
```fs.readFileSync('uploads/' + req.files.image.name)```
req.files.image doesn't exist. This code runs under the assumption that a file will be submitted with a image in the form data, but I didn't and it caused it to crash.

**Comment by vanessachen** [comment]
Oh ok cool thanks. How come you sent it to me though?

**Comment by AJNDL** [comment]
@vanessachen sorry! I didn't mean to. If you happen to be watching this repository, I would imagine that it would notify you when a new issue is created...

**Comment by vanessachen** [comment]
Oh ok cool I see. Well have fun with the rest of your evening then!

**Comment by nacgarg** [comment]
I added a simple if statement that should fix it.
